global:
  - CI=true
  - CC_TEST_REPORTER_ID=d570e2625aaffa20e7828eaddfbec748c525e866b6d413472bc26e188cb2bc6a
  - DATABASE_URL_TEST=postgres://postgres@localhost:5432/barefootnomaddb_test
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE barefoot;' -U postgres
  - npm i sequelize-cli -g
  - npm i sequelize -g
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coveralls
